version: 1.0.{build}

platform: x64

# `git clone` takes ages due to the repo's size
shallow_clone: true

image:
- Windows Server 2019
- Visual Studio 2017

environment:
  matrix:
    - PLATFORM: windows-sac2016
      PLATFORM_DIR: ./windows/sac2016/
    - PLATFORM: windows-1809
      PLATFORM_DIR: ./windows/1809/


matrix:
  fast_finish: true
  exclude:
    - image: Windows Server 2019
      PLATFORM: windows-sac2016
    - image: Visual Studio 2017
      PLATFORM: windows-1809

build_script:
  - ps: |
      $ErrorActionPreference = 'Stop' # Fail if any instruction fails
      docker build -t traefik:$env:PLATFORM $env:PLATFORM_DIR
      docker run --name lb -d -p 8080:8080 traefik:$env:PLATFORM --api
      sleep 2
      docker ps
      Invoke-WebRequest -Uri http://localhost:8080 -TimeoutSec 60
